# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool: DemoAg
variables:
  imageName: 'lalitkr2506/azurerepo:$(build.buildNumber)'

  
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: DemoAg
      demands:
        - Agent.Name -equals Agent-1
    steps:
      - task: MSBuild@1
        inputs:
          solution: '**/*.sln'
          msbuildArchitecture: 'x64'
          restoreNugetPackages: true
          createLogFile: true
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'azSonar'
          scannerMode: 'MSBuild'
          projectKey: 'mytestproject_dotnet-job'
          projectName: 'DemoProject'
      - task: SonarQubeAnalyze@5
      - task: Docker@1
        displayName: 'Build an image'
        inputs:
          command: Build an image
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: dockerHub
          dockerFile: Dockerfile
          imageName: $(imageName)
          restartPolicy: always
      
      
      - task: Docker@1
        displayName: 'Push an image'
        inputs:
          command: Push an image
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: dockerHub
          dockerFile: Dockerfile
          imageName: $(imageName)
          restartPolicy: always
- stage: Deployment
  displayName: Deployment
  jobs:
  - job: Deploy
    pool:
      name: 'DemoAg'
      demands:
        - Agent.Name -equals Deployment
    steps:
       - task: CmdLine@2
         inputs:
           script: 'docker run -itd $(imageName)'
