# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

resources:
   repositories:
     - repository: 'DocnetCoreWebappDockerCICD' 
       type: github
       endpoint: 'github.com_ItsMePri02'
       name: ItsMePri02/DocnetCoreWebappDockerCICD
       #ref: master
       trigger:
         branches:
           include:
            - master
            - Dev/*
            - QA/*

pool:
  vmImage: 'windows-latest'

stages:

- ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:

  - stage: master

    jobs:

    - job: masterjob

      pool:

        vmImage: ubuntu-latest

      steps:

        - task: Bash@3

          displayName: master

          inputs:

            targetType: inline

            script: |

              echo "triggered by ${Build.SourceBranchName}"

              echo "master"



- ${{ elseif eq( variables['Build.SourceBranchName'], 'Dev' ) }}:

  - stage: stage2

    jobs:

    - job: dev_repo

      steps:

        - task: Bash@3

          displayName: dev_repo

          inputs:

            targetType: inline

            script: |

              echo "triggered by $(Build.SourceBranchName)"

              echo "dev"

