# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev
- QA

variables:
  imageName: 'lalitkr2506/azurerepo:$(build.buildNumber)'

  
stages:

- ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:

  - stage: master

    jobs:

    - job: masterjob

      pool:

        vmImage: ubuntu-latest

      steps:

        - task: Bash@3

          displayName: master

          inputs:

            targetType: inline

            script: |

              echo "triggered by ${Build.SourceBranchName}"

              echo "master"



- ${{ elseif eq( variables['Build.SourceBranchName'], 'Dev' ) }}:

  - stage: stage2

    jobs:

    - job: dev_repo

      steps:

        - task: Bash@3

          displayName: dev_repo

          inputs:

            targetType: inline

            script: |

              echo "triggered by $(Build.SourceBranchName)"

              echo "dev"

- ${{ elseif eq( variables['Build.SourceBranchName'], 'QA' ) }}:

  - stage: stage3

    jobs:

    - job: QA_repo

      steps:

        - task: Bash@3

          displayName: QA_repo

          inputs:

            targetType: inline

            script: |

              echo "triggered by $(Build.SourceBranchName)"

              echo "QA"
